name: Run tests
on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  chrome-tests:
    name: Run Chrome e2e tests
    # Runs best on macos for CI as linux requires extra chrome flags
    runs-on: macos-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: NPM install
        run: npm install
      - name: Run server
        run: npm run test:server &
      - name: Run e2e tests for chrome
        run: npm run test:e2e -- --browsers=chrome
  firefox-tests:
    name: Run Firefox e2e tests
    # Runs best on macos for CI as linux requires extra setup
    runs-on: macos-latest
    env:
      MOZ_PROFILER_STARTUP_FILTERS: "*"
      MOZ_PROFILER_STARTUP: "1"
      MOZ_PROFILER_SHUTDOWN: "/tmp/profiler.json"
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: NPM install
        run: npm install
      - name: Run server
        run: npm run test:server &
      - name: Run e2e tests for firefox
        run: npm run test:e2e -- --browsers=firefox
        continue-on-error: true
      - name: Upload profile artifact
        uses: actions/upload-artifact@v3
        with:
          name: profile.json
          path: /tmp/profiler.json
      - name: Echo profile location
        run: echo "Profiler should be available at https://api.github.com/repos/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}/artifacts/profiler.json"
  safari-tests:
    name: Run Safari e2e tests
    # Requires macos
    runs-on: macos-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: NPM install
        run: npm install
      - name: Run server
        run: npm run test:server &
      - name: Run e2e tests for safari
        run: npm run test:e2e -- --browsers=safari
